# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymGram2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseMessaging'
  pod 'FirebaseAuth'
  pod 'ActiveLabel'
  pod 'Firebase/Messaging'

  # Pods for GymGram2

  target 'GymGram2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GymGram2UITests' do
    # Pods for testing
  end

end
