# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# created by Kamel Shaaban

target 'Gymgram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gymgram

pod 'Appirater'
pod 'SDWebImage'
# for my Firebase dependencies

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FirebaseUI/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'



end
